### PR TITLE
Fixed initialization issue in autocomplete widget

### PR DESCRIPTION
**Pull request by ritchiecarroll**
Fix for puiautocomplete initialization error #220

### CODE REVIEW

**Comment by ritchiecarroll** [comment]
Example of error:
capture

**Comment by cagataycivici** [comment]
Doesn't the patch remove '<div class="ui-autocomplete-panel ui-widget-content ui-corner-all ui-helper-hidden ui-shadow"></div>'? from panel

**Comment by ritchiecarroll** [comment]
Panel was just added, so innerHTML should be blank at that point in the process anyway, so the "this.panel.html('');" line could safely be dropped. I just copied those three lines of initialization code from further down to make sure "items" property exists because call to keydown event.

**Comment by ritchiecarroll** [comment]
Closing to re-add pull request against new branch - also working on fiddle to reproduce...

**Comment by StephenCWills** [comment]
While working on the jsfiddle to reproduce this issue, we discovered the page was missing jquery-ui.css. Adding the stylesheet to the page fixed the issue so this was a false alarm.

**Pull request closed without merging**
